Amal/feat/quote plugin
allink/allink-core pull request #21
Opened 2019-11-15 15:39 UTC by mariuskueng

2019-11-15 15:41 UTC, tuerlefl requested changes
changes in MANIFEST.in and CHANGELOG.md are currently missing.

2019-11-15 15:51 UTC, mariuskueng commented
🤦‍♂ Updated the MANIFEST.in. Shouldn't we make CHANGELOG updates in a separate commit?

2019-11-16 11:57 UTC, tuerlefl commented
we can make a separate commit, but i think it would make sense to keep the changes and the CHANGELOG update together.

2019-11-19 14:45 UTC, tuerlefl approved these changes

2019-11-19 15:25 UTC, merged