Disable image loading icon by default
allink/allink-core pull request #55
Opened 2020-03-19 11:34 UTC by slavanga

2020-03-19 11:35 UTC, tuerlefl approved these changes

2020-03-19 11:35 UTC, tuerlefl requested changes
we need migrations for this change

2020-03-24 10:49 UTC, slavanga commented
@tuerlefl migrations added

2020-03-24 10:56 UTC, tuerlefl approved these changes

2020-03-24 10:58 UTC, merged